### ISSUE TITLE
cannot figure out how to use mouse.on_double_click on Windows 

### ISSUE THREAD

**Issue by redstoneleo** [boppreh/mouse#11] opened 2017-12-03 22:37 UTC
With the following code, I think the `sayHello` function should print out something when double clicking  left mouse button , but none , so what's wrong here ?
```
import mouse


def sayHello():
    print(mouse.get_position(),'sayHello')
mouse.on_double_click(sayHello)  # lambda: print(11111111111) callback, args=()

mouse.wait(button='left', target_types=('double',))

```

**Comment by boppreh** [comment] 2017-12-03 22:39
Duplicate of #3 . Sorry, my fault for not yet releasing a new version with that commit. As a temporary workaround, you can use the latest version from the master branch.

**Closed by boppreh** 2017-12-03 22:39 UTC

**Comment by redstoneleo** [comment] 2017-12-04 00:03
Thanks very much , great project !!!
